// settings/list/item/options/index.vue
<template>
  <SpeedDial
    :model="items"
    direction="left"
    class="modules-settings-options"
    @click.stop
  >
    <template #button="{ toggleCallback }">
      <ad-button
        text
        rounded
        icon="prime:ellipsis-h"
        :ad-type="props.enabled && 'main'"
        :severity="!props.enabled && 'secondary'"
        @click="toggleCallback"
      />
    </template>
    <template #item="{ item, toggleCallback }">
      <div @click="toggleCallback">
        <ad-icon
          :icon="item.icon"
          @click="item.command"
          v-tooltip.top="item.label"
        />
      </div>
    </template>
  </SpeedDial>

  <nuc-modules-item-options-dialog
    v-model:visible="dialogVisible"
    :name="props.name"
    :enabled="props.enabled"
    :action="currentAction"
    @confirm="confirmAction"
  />
</template>

<script setup lang="ts">
import {
  moduleRequests,
  ModuleDialogAction,
  NucModulesItemOptionsDialog,
  ModuleObjectInterface,
} from 'nucleify'

const props = defineProps<ModuleObjectInterface>()
const emit = defineEmits(['moduleToggled', 'moduleUninstalled'])

const route = useRoute()
const router = useRouter()
const locale = computed(() => String(route.params.lang || 'en'))

const { installModule, toggleModule, uninstallModule } = moduleRequests()

const dialogVisible = ref(false)
const currentAction = ref<ModuleDialogAction>('uninstall')

const openDialog = (action: ModuleDialogAction) => {
  currentAction.value = action
  dialogVisible.value = true
}

const confirmAction = (options?: { deleteModuleFiles?: boolean }) => {
  if (currentAction.value === 'install') {
    installModule(props.name, () => emit('moduleUninstalled'))
  } else if (currentAction.value === 'uninstall') {
    uninstallModule(
      props.name,
      () => emit('moduleUninstalled'),
      options?.deleteModuleFiles === true
    )
  } else {
    toggleModule(props.name, props.enabled, () => emit('moduleToggled'))
  }
}

const items = computed(() => [
  {
    label: 'Show',
    icon: 'prime:info-circle',
    command: () => {
      router.push(`/${locale.value}/settings#module-${props.name}`)
    },
  },
  {
    label: props.enabled ? 'Disable' : 'Enable',
    icon: props.enabled ? 'prime:times-circle' : 'prime:check-circle',
    command: () => openDialog('toggle'),
  },
  {
    label: props.installed ? 'Uninstall' : 'Install',
    icon: props.installed ? 'prime:trash' : 'prime:download',
    command: () => openDialog(props.installed ? 'uninstall' : 'install'),
  },
])
</script>

<style lang="scss">
@import 'index'
</style>

// settings/list/item/options/index.tsx
'use client'

import { useRouter } from 'next/navigation'
import type { MenuItem, MenuItemCommandEvent } from 'primereact/menuitem'
import { useCallback, useEffect, useMemo, useState } from 'react'

import type { ModuleDialogAction } from 'nucleify'
import {
  AdButton,
  AdIcon,
  AdSpeedDial,
  flashToast,
  moduleRequests,
  NucModulesItemOptionsDialog,
  NucModulesItemOptionsInterface,
} from 'nucleify'

import './_index.scss'

const { installModule, toggleModule, uninstallModule } = moduleRequests()

function isModuleInstalled(installed: boolean | undefined): boolean {
  return installed === true
}

function buildSpeedDialItem(
  label: string,
  icon: string,
  onSelect: () => void
): MenuItem {
  return {
    label,
    icon,
    command: (event: MenuItemCommandEvent) => {
      event.originalEvent?.stopPropagation()
      onSelect()
    },
    template: (item, options) => (
      <div
        role="presentation"
        onClick={(event) => {
          event.stopPropagation()
          options.onClick(event)
        }}
      >
        <AdIcon icon={String(item.icon ?? icon)} />
      </div>
    ),
  }
}

export function NucModulesItemOptions({
  name,
  enabled,
  installed,
  onModuleToggled,
  onModuleUninstalled,
}: NucModulesItemOptionsInterface) {
  const router = useRouter()
  const [localInstalled, setLocalInstalled] = useState(() =>
    isModuleInstalled(installed)
  )
  const [localEnabled, setLocalEnabled] = useState(enabled === true)

  useEffect(() => {
    setLocalInstalled(isModuleInstalled(installed))
  }, [installed, name])

  useEffect(() => {
    setLocalEnabled(enabled === true)
  }, [enabled, name])

  const [dialogVisible, setDialogVisible] = useState(false)
  const [currentAction, setCurrentAction] = useState<ModuleDialogAction>(
    localInstalled ? 'uninstall' : 'install'
  )

  useEffect(() => {
    setCurrentAction(localInstalled ? 'uninstall' : 'install')
  }, [localInstalled])

  const openDialog = useCallback((action: ModuleDialogAction) => {
    setCurrentAction(action)
    setDialogVisible(true)
  }, [])

  const handleConfirm = useCallback(
    async (options?: { deleteModuleFiles?: boolean }) => {
      if (!name) {
        flashToast('Module name is required', 'error')
        return
      }

      if (currentAction === 'install') {
        await installModule(name, () => {
          setLocalInstalled(true)
          setLocalEnabled(true)
          void onModuleUninstalled?.()
        })
        return
      }

      if (currentAction === 'uninstall') {
        await uninstallModule(
          name,
          () => {
            setLocalInstalled(false)
            setLocalEnabled(false)
            void onModuleUninstalled?.()
          },
          options?.deleteModuleFiles === true
        )
        return
      }

      const nextEnabled = !localEnabled
      setLocalEnabled(nextEnabled)

      await toggleModule(name, localEnabled, () => {
        void onModuleToggled?.()
      })
    },
    [currentAction, localEnabled, name, onModuleToggled, onModuleUninstalled]
  )

  const model: MenuItem[] = useMemo(
    () => [
      buildSpeedDialItem('Show', 'prime:info-circle', () => {
        void router.push(`/settings#module-${name}`)
      }),
      buildSpeedDialItem(
        localEnabled ? 'Disable' : 'Enable',
        localEnabled ? 'prime:times-circle' : 'prime:check-circle',
        () => openDialog('toggle')
      ),
      buildSpeedDialItem(
        localInstalled ? 'Uninstall' : 'Install',
        localInstalled ? 'prime:trash' : 'prime:download',
        () => openDialog(localInstalled ? 'uninstall' : 'install')
      ),
    ],
    [localEnabled, localInstalled, name, openDialog, router]
  )

  return (
    <div
      onClick={(event) => event.stopPropagation()}
      onKeyDown={(event) => event.stopPropagation()}
      role="presentation"
    >
      <AdSpeedDial
        key={`${name}-${localInstalled ? 'installed' : 'uninstalled'}-${localEnabled ? 'enabled' : 'disabled'}`}
        model={model}
        direction="left"
        className="modules-settings-options"
        buttonTemplate={(opts) => (
          <AdButton
            text
            rounded
            icon="prime:ellipsis-h"
            nuiType={localEnabled ? 'main' : undefined}
            severity={localEnabled ? undefined : 'secondary'}
            type="button"
            onClick={(event) => {
              event.stopPropagation()
              opts.onClick?.(event)
            }}
          />
        )}
      />

      <NucModulesItemOptionsDialog
        visible={dialogVisible}
        onHide={() => setDialogVisible(false)}
        name={name}
        enabled={localEnabled}
        action={currentAction}
        onConfirm={handleConfirm}
      />
    </div>
  )
}
