// atomic/templates/readme/index.tsx
'use client'

import { useEffect, useState } from 'react'

import type { ModuleReadmeInterface } from 'nucleify'
import { loadReadme } from 'nucleify'

import './_index.scss'

export function NucModulesReadme({
  modulePath,
  readmeContent: readmeContentProp,
  showLoading = false,
}: ModuleReadmeInterface) {
  const [readmeContent, setReadmeContent] = useState('')
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    let cancelled = false

    async function run(): Promise<void> {
      if (modulePath) {
        setLoading(true)
        await loadReadme(
          modulePath,
          (html) => {
            if (!cancelled) {
              setReadmeContent(html)
              setLoading(false)
            }
          },
          () => {
            if (!cancelled) {
              setReadmeContent('')
              setLoading(false)
            }
          }
        )
      } else if (readmeContentProp) {
        setReadmeContent(readmeContentProp)
        setLoading(false)
      } else {
        setReadmeContent('')
        setLoading(false)
      }
    }

    void run()

    return () => {
      cancelled = true
    }
  }, [modulePath, readmeContentProp])

  if (readmeContent) {
    return (
      <div
        className="readme-content"
        dangerouslySetInnerHTML={{ __html: readmeContent }}
      />
    )
  }

  if (loading || showLoading) {
    return (
      <div className="readme-loading">
        <p>Loading documentation...</p>
      </div>
    )
  }

  return null
}

// atomic/template/readme/index.vue
<template>
  <div v-if="readmeContent" class="readme-content" v-html="readmeContent"></div>
  <div v-else-if="loading || showLoading" class="readme-loading">
    <p>Loading documentation...</p>
  </div>
</template>

<script setup lang="ts">
import { loadReadme } from 'nucleify'

export interface ModuleReadmeInterface {
  modulePath?: string
  readmeContent?: string
  showLoading?: boolean
}

const props = withDefaults(defineProps<ModuleReadmeInterface>(), {
  showLoading: false,
})

const readmeContent = ref<string>('')
const loading = ref(false)

watch(
  () => props.modulePath,
  async () => {
    if (props.modulePath) {
      loading.value = true
      await loadReadme(
        props.modulePath,
        (html: string) => {
          readmeContent.value = html
          loading.value = false
        },
        () => {
          readmeContent.value = ''
          loading.value = false
        }
      )
    } else if (props.readmeContent) {
      readmeContent.value = props.readmeContent
    } else {
      readmeContent.value = ''
    }
  },
  { immediate: true }
)

watch(
  () => props.readmeContent,
  (newContent: string | undefined) => {
    if (newContent && !props.modulePath) {
      readmeContent.value = newContent
    }
  }
)
</script>

<style lang="scss">
@import '.'
</style>
