// settings/list/index.tsx
'use client'

import type { NucModulesListInterface } from 'nucleify'
import { NucModulesSettingsItem } from 'nucleify'

import './_index.scss'

export function NucModulesList({
  data,
  onModuleToggled,
  onModuleUninstalled,
}: NucModulesListInterface) {
  return (
    <div className="modules-settings-list">
      {data.map((module) => (
        <NucModulesSettingsItem
          key={module.name}
          {...module}
          onModuleToggled={onModuleToggled}
          onModuleUninstalled={onModuleUninstalled}
        />
      ))}
    </div>
  )
}

// settings/list/index.vue
<template>
  <div class="modules-settings-list">
    <nuc-modules-settings-item
      v-for="module in props.data"
      v-bind="module"
      :key="module.name"
      @module-toggled="emit('moduleToggled')"
      @module-uninstalled="emit('moduleUninstalled')"
    />
  </div>
</template>

<script setup lang="ts">
import type { NucModulesListInterface } from 'nucleify'
import { NucModulesSettingsItem } from 'nucleify'

const props = defineProps<NucModulesListInterface>()
const emit = defineEmits(['moduleToggled', 'moduleUninstalled'])
</script>

<style lang="scss">
@import 'index';
</style>
