// settings/install/index.tsx
'use client'

import type { FileUploadFile, ItemTemplateOptions } from 'primereact/fileupload'
import { useState } from 'react'

import type { NucModulesSettingsInstallModuleInterface } from 'nucleify'
import { AdButton, AdDialog, AdFileUpload, useInstallModule } from 'nucleify'

import './_index.scss'

export function NucModulesSettingsInstallModule({
  onModuleInstalled,
}: NucModulesSettingsInstallModuleInterface) {
  const [visible, setVisible] = useState(false)

  const { onBeforeUpload, onUpload, onError, formatSize } = useInstallModule(
    () => {
      setVisible(false)
      onModuleInstalled?.()
    }
  )

  return (
    <>
      <AdButton
        adType="main"
        text
        rounded
        icon="prime:upload"
        className="install-module-button"
        type="button"
        onClick={() => setVisible(true)}
      />

      <AdDialog
        visible={visible}
        onHide={() => setVisible(false)}
        modal
        dismissableMask
        showHeader={false}
        className="install-module-dialog"
      >
        <AdFileUpload
          name="file"
          url="/api/modules/install"
          maxFileSize={1_000_000}
          withCredentials
          onBeforeUpload={onBeforeUpload}
          onUpload={onUpload}
          onError={onError}
          emptyTemplate={<span>Drag and drop files to here to upload.</span>}
          itemTemplate={(file: object, _options: ItemTemplateOptions) => {
            const f = file as FileUploadFile
            return (
              <div key={f.name}>
                <span>{f.name}</span>
                <div>{formatSize(f.size ?? 0)}</div>
              </div>
            )
          }}
        />
      </AdDialog>
    </>
  )
}

// settings/install/index.vue
<template>
  <ad-button
    ad-type="main"
    text
    rounded
    icon="prime:upload"
    class="install-module-button"
    @click="visible = true"
  />

  <Dialog
    v-model:visible="visible"
    :modal="true"
    :dismissable-mask="true"
    class="install-module-dialog"
  >
    <template #default>
      <FileUpload
        name="file"
        :url="'/api/modules/install'"
        :maxFileSize="1000000"
        :withCredentials="true"
        @before-upload="beforeUpload"
        @upload="onUpload"
        @error="onError"
      >
        <template #empty>
          <span>Drag and drop files to here to upload.</span>
        </template>
        <template
          #header="{ chooseCallback, uploadCallback, clearCallback, files }"
        >
          <ad-button
            text
            ad-type="main"
            icon="prime:upload"
            @click="chooseCallback()"
            :disabled="files && files.length > 0"
          >
            <label>Choose</label>
          </ad-button>
          <ad-button
            text
            severity="success"
            icon="prime:cloud-upload"
            :disabled="!files || files.length === 0"
            @click="uploadCallback()"
          >
            <label>Upload</label>
          </ad-button>
          <ad-button
            severity="secondary"
            text
            icon="prime:times"
            :disabled="!files || files.length === 0"
            @click="clearCallback()"
          >
            <label>Clear</label>
          </ad-button>
        </template>
        <template #content="slotProps">
          <div v-for="file in slotProps.files" :key="file.name">
            <span>{{ file.name }}</span>
            <div>{{ formatSize(file.size) }}</div>
          </div>
        </template>
      </FileUpload>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue'

import { useInstallModule } from 'nucleify'

const visible = ref(false)

const emit = defineEmits<{
  moduleInstalled: []
}>()

const {
  beforeUpload,
  onUpload: handleUpload,
  onError,
  formatSize,
} = useInstallModule((): void => {
  visible.value = false
  emit('moduleInstalled')
})

function onUpload(): void {
  handleUpload()
}
</script>

<style lang="scss">
@import 'index';
</style>
