// settings/list/item/index.vue
<template>
  <div class="modules-settings-item" :class="{ 'active': props.enabled }">
    <a
      class="modules-settings-item-link"
      :href="`/settings#module-${props.name}`"
    >
      <nuc-cube
        :shiny="props.enabled"
        v-tooltip.right="props.enabled ? 'Enabled' : 'Disabled'"
      />
      <div class="modules-settings-item-container">
        <div class="modules-settings-item-info">
          <label>{{ props.name }}</label>
          <p>{{ props.description }}</p>
        </div>
      </div>
    </a>
    <nuc-modules-item-options
      v-bind="props"
      @module-toggled="emit('moduleToggled')"
      @module-uninstalled="emit('moduleUninstalled')"
    />
  </div>
</template>

<script setup lang="ts">
import type { ModuleObjectInterface } from 'nucleify'

import { NucModulesItemOptions } from '.'

const props = defineProps<ModuleObjectInterface>()
const emit = defineEmits(['moduleToggled', 'moduleUninstalled'])
</script>

<style lang="scss">
@import 'index';
</style>

// settings/list/item/index.tsx
'use client'

import { useParams } from 'next/navigation'

import type { NucModulesItemOptionsInterface } from 'nucleify'
import { NucCube, NucModulesItemOptions } from 'nucleify'

import './_index.scss'

export function NucModulesSettingsItem({
  onModuleToggled,
  onModuleUninstalled,
  ...module
}: NucModulesItemOptionsInterface) {
  const params = useParams<{ lang?: string }>()
  const lang = params?.lang ?? 'en'

  return (
    <div className={`modules-settings-item${module.enabled ? ' active' : ''}`}>
      <a
        className="modules-settings-item-link"
        href={`/${lang}/settings#module-${module.name}`}
      >
        <span
          title={module.enabled ? 'Enabled' : 'Disabled'}
          style={{ display: 'inline-flex' }}
        >
          <NucCube shiny={module.enabled} />
        </span>
        <div className="modules-settings-item-container">
          <div className="modules-settings-item-info">
            <label>{module.name}</label>
            <p>{module.description}</p>
          </div>
        </div>
      </a>
      <NucModulesItemOptions
        {...module}
        onModuleToggled={onModuleToggled}
        onModuleUninstalled={onModuleUninstalled}
      />
    </div>
  )
}
