// settings/dialog/readme/index.tsx
'use client'

import type { ModuleReadmeDialogComponentProps } from 'nucleify'
import { AdButton, AdDialog, NucModulesReadme } from 'nucleify'

import './_index.scss'

export function NucModulesSettingsDetailReadmeDialog({
  modulePath,
  visible,
  onHide,
}: ModuleReadmeDialogComponentProps) {
  return (
    <AdDialog
      visible={visible}
      onHide={onHide}
      modal
      dismissableMask
      showHeader={false}
      className="modules-settings-readme-dialog"
      footer={
        <AdButton
          label="Close"
          icon="prime:times"
          severity="secondary"
          text
          rounded
          type="button"
          onClick={onHide}
        />
      }
    >
      <NucModulesReadme modulePath={modulePath} showLoading />
    </AdDialog>
  )
}

// settings/dialog/readme/index.vue
<template>
  <ad-dialog
    v-model:visible="visible"
    class="modules-settings-readme-dialog"
    :modal="true"
    :dismissable-mask="true"
  >
    <nuc-modules-readme :module-path="props.modulePath" :show-loading="true" />
    <template #footer>
      <ad-button
        label="Close"
        icon="prime:times"
        severity="secondary"
        @click="visible = false"
      />
    </template>
  </ad-dialog>
</template>

<script setup lang="ts">
import { NucModulesReadme } from 'nucleify'
import type { ModuleReadmeDialogInterface } from 'nucleify'

const props = defineProps<ModuleReadmeDialogInterface>()
const visible = defineModel<boolean>('visible', { default: false })
</script>

<style lang="scss">
@import 'index';
</style>
