// settings/uninstall/index.vue
<template>
  <ad-button
    ad-type="main"
    text
    rounded
    icon="prime:trash"
    class="uninstall-module-button"
    @click="uninstallModule(props.name, () => emit('moduleUninstalled'))"
  />
</template>

<script setup lang="ts">
import { moduleRequests } from 'nucleify'
import type { NucModulesUninstallModuleInterface } from 'nucleify'

const props = defineProps<NucModulesUninstallModuleInterface>()

const emit = defineEmits<{
  moduleUninstalled: []
}>()

const { uninstallModule } = moduleRequests()
</script>

<style lang="scss">
@import 'index';
</style>

// settings/uninstall/index.tsx
'use client'

import type { NucModulesUninstallModuleInterface } from 'nucleify'
import { AdButton, moduleRequests } from 'nucleify'

import './_index.scss'

export default function NucModulesSettingsUninstallModule({
  name,
  onModuleUninstalled,
}: NucModulesUninstallModuleInterface) {
  const { uninstallModule } = moduleRequests()

  return (
    <AdButton
      nuiType="main"
      text
      rounded
      icon="prime:trash"
      className="uninstall-module-button"
      type="button"
      onClick={() => void uninstallModule(name, () => onModuleUninstalled?.())}
    />
  )
}
