// settings/dialog/item-options/index.tsx
'use client'

import { useMemo, useState } from 'react'

import type { ModuleItemOptionsDialogInterface } from 'nucleify'
import { AdButton, AdCheckbox, AdDialog, t } from 'nucleify'

import './_index.scss'

export function NucModulesItemOptionsDialog({
  visible,
  onHide,
  name,
  enabled,
  action,
  onConfirm,
}: ModuleItemOptionsDialogInterface) {
  const [deleteModuleFiles, setDeleteModuleFiles] = useState(false)

  const config = useMemo(() => {
    if (action === 'install') {
      return {
        header: 'Confirm Install',
        actionVerb: 'install',
        label: 'Install',
        icon: 'prime:download',
        severity: 'success' as const,
      }
    }

    if (action === 'uninstall') {
      return {
        header: 'Confirm Uninstall',
        actionVerb: 'uninstall',
        label: 'Uninstall',
        icon: 'prime:trash',
        severity: 'danger' as const,
      }
    }

    return {
      header: enabled ? 'Confirm Disable' : 'Confirm Enable',
      actionVerb: enabled ? 'disable' : 'enable',
      label: enabled ? 'Disable' : 'Enable',
      icon: enabled ? 'prime:times-circle' : 'prime:check-circle',
      severity: 'secondary' as const,
    }
  }, [action, enabled])

  function handleConfirm(): void {
    onHide()

    if (action === 'uninstall') {
      void onConfirm({ deleteModuleFiles })
      setDeleteModuleFiles(false)
      return
    }

    void onConfirm()
  }

  return (
    <AdDialog
      visible={visible}
      onHide={onHide}
      modal
      header={config.header}
      className="modules-settings-options-dialog"
      footer={
        <>
          <AdButton
            label="Cancel"
            icon="prime:times"
            severity="secondary"
            text
            rounded
            type="button"
            onClick={onHide}
          />
          <AdButton
            label={config.label}
            icon={config.icon}
            severity={config.severity}
            adType="main"
            text
            rounded
            type="button"
            onClick={handleConfirm}
          />
        </>
      }
    >
      <p>
        Are you sure you want to {config.actionVerb} <strong>{name}</strong>?
      </p>
      {action === 'uninstall' ? (
        <div className="modules-settings-options-dialog__delete-files">
          <AdCheckbox
            inputId="delete-module-files"
            checked={deleteModuleFiles}
            onChange={(event) => setDeleteModuleFiles(event.checked === true)}
          />
          <label
            htmlFor="delete-module-files"
            className="modules-settings-options-dialog__delete-files-label"
          >
            {t('modules-uninstall-delete-files-label')}
          </label>
          <p className="modules-settings-options-dialog__delete-files-hint">
            {t('modules-uninstall-delete-files-hint')}
          </p>
        </div>
      ) : null}
    </AdDialog>
  )
}

// settings/dialog/item-options/index.vue
<template>
  <ad-dialog
    v-model:visible="visible"
    class="modules-settings-options-dialog"
    :modal="true"
    :header="config.header"
  >
    <p>
      Are you sure you want to {{ config.actionVerb }}
      <strong>{{ props.name }}</strong>?
    </p>
    <div
      v-if="props.action === 'uninstall'"
      class="modules-settings-options-dialog__delete-files"
    >
      <ad-checkbox
        v-model="deleteModuleFiles"
        binary
        input-id="delete-module-files"
      />
      <label
        for="delete-module-files"
        class="modules-settings-options-dialog__delete-files-label"
      >
        {{ t('modules-uninstall-delete-files-label') }}
      </label>
      <p class="modules-settings-options-dialog__delete-files-hint">
        {{ t('modules-uninstall-delete-files-hint') }}
      </p>
    </div>
    <template #footer>
      <ad-button
        label="Cancel"
        icon="prime:times"
        severity="secondary"
        text
        rounded
        @click="visible = false"
      />
      <ad-button
        :label="config.label"
        :icon="config.icon"
        :severity="config.severity"
        ad-type="main"
        text
        rounded
        @click="handleConfirm"
      />
    </template>
  </ad-dialog>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import type { ModuleDialogInterface } from 'nucleify'

const props = defineProps<ModuleDialogInterface>()
const visible = defineModel<boolean>('visible', { default: false })
const emit = defineEmits<{
  confirm: [payload?: { deleteModuleFiles?: boolean }]
}>()

const { t } = useI18n()
const deleteModuleFiles = ref(false)

const config = computed(() => {
  if (props.action === 'install') {
    return {
      header: 'Confirm Install',
      actionVerb: 'install',
      label: 'Install',
      icon: 'prime:download',
      severity: 'success' as const,
    }
  }

  if (props.action === 'uninstall') {
    return {
      header: 'Confirm Uninstall',
      actionVerb: 'uninstall',
      label: 'Uninstall',
      icon: 'prime:trash',
      severity: 'danger' as const,
    }
  }

  return {
    header: props.enabled ? 'Confirm Disable' : 'Confirm Enable',
    actionVerb: props.enabled ? 'disable' : 'enable',
    label: props.enabled ? 'Disable' : 'Enable',
    icon: props.enabled ? 'prime:times-circle' : 'prime:check-circle',
    severity: 'secondary' as const,
  }
})

function handleConfirm(): void {
  visible.value = false

  if (props.action === 'uninstall') {
    emit('confirm', { deleteModuleFiles: deleteModuleFiles.value })
    deleteModuleFiles.value = false
    return
  }

  emit('confirm')
}
</script>

<style lang="scss">
@import 'index';
</style>
